// AUTO-GENERATED by scripts/bundle-migrations.mjs — do not edit.
export interface Migration {
  tag: string;
  statements: string[];
}

export const MIGRATIONS: Migration[] = [
  {
    tag: '0000_known_mephisto',
    statements: [
      'CREATE TABLE `ability_ratings` (\n\t`module` text PRIMARY KEY NOT NULL,\n\t`elo` real NOT NULL,\n\t`updated_at` integer NOT NULL\n);',
      'CREATE TABLE `assessments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`instrument` text NOT NULL,\n\t`raw_score` real NOT NULL,\n\t`normalized` real,\n\t`ts` integer NOT NULL\n);',
      'CREATE TABLE `cards` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`module` text NOT NULL,\n\t`front` text NOT NULL,\n\t`back` text NOT NULL,\n\t`payload` text,\n\t`created_at` integer NOT NULL,\n\t`is_synced` integer DEFAULT false NOT NULL,\n\t`is_deleted` integer DEFAULT false NOT NULL\n);',
      'CREATE INDEX `cards_module_is_deleted_idx` ON `cards` (`module`,`is_deleted`);',
      'CREATE TABLE `fsrs_state` (\n\t`card_id` text PRIMARY KEY NOT NULL,\n\t`due` integer NOT NULL,\n\t`stability` real NOT NULL,\n\t`difficulty` real NOT NULL,\n\t`reps` integer NOT NULL,\n\t`lapses` integer NOT NULL,\n\t`phase` text NOT NULL,\n\t`scheduled_days` integer NOT NULL,\n\t`learning_steps` integer NOT NULL,\n\t`last_review` integer,\n\tFOREIGN KEY (`card_id`) REFERENCES `cards`(`id`) ON UPDATE no action ON DELETE no action\n);',
      'CREATE INDEX `fsrs_state_due_idx` ON `fsrs_state` (`due`);',
      'CREATE TABLE `review_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`card_id` text NOT NULL,\n\t`ts` integer NOT NULL,\n\t`rating` text NOT NULL,\n\t`elapsed_ms` integer NOT NULL,\n\t`difficulty` real NOT NULL,\n\t`stability` real NOT NULL,\n\t`retrievability` real NOT NULL,\n\tFOREIGN KEY (`card_id`) REFERENCES `cards`(`id`) ON UPDATE no action ON DELETE no action\n);',
      'CREATE INDEX `review_log_card_id_idx` ON `review_log` (`card_id`);',
      'CREATE INDEX `review_log_ts_idx` ON `review_log` (`ts`);',
      'CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`started` integer NOT NULL,\n\t`ended` integer,\n\t`module` text NOT NULL,\n\t`items` integer DEFAULT 0 NOT NULL,\n\t`accuracy` real DEFAULT 0 NOT NULL\n);',
    ],
  },
  {
    tag: '0001_review_log_append_only',
    statements: [
      "CREATE TRIGGER review_log_no_update BEFORE UPDATE ON review_log\nBEGIN\n  SELECT RAISE(ABORT, 'review_log is append-only');\nEND;",
      "CREATE TRIGGER review_log_no_delete BEFORE DELETE ON review_log\nBEGIN\n  SELECT RAISE(ABORT, 'review_log is append-only');\nEND;",
    ],
  },
  {
    tag: '0002_robust_arclight',
    statements: ['ALTER TABLE `assessments` ADD `payload` text;'],
  },
  {
    tag: '0003_tranquil_guardsmen',
    statements: [
      'CREATE TABLE `loci` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`palace_id` text NOT NULL,\n\t`position` integer NOT NULL,\n\t`label` text NOT NULL,\n\t`cue` text,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`palace_id`) REFERENCES `palaces`(`id`) ON UPDATE no action ON DELETE no action\n);',
      'CREATE INDEX `loci_palace_id_idx` ON `loci` (`palace_id`);',
      'CREATE UNIQUE INDEX `loci_palace_position_unq` ON `loci` (`palace_id`,`position`);',
      'CREATE TABLE `palaces` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`is_deleted` integer DEFAULT false NOT NULL\n);',
    ],
  },
  {
    tag: '0004_long_white_tiger',
    statements: [
      'CREATE TABLE `ability_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`module` text NOT NULL,\n\t`elo` real NOT NULL,\n\t`ts` integer NOT NULL\n);',
      'CREATE INDEX `ability_log_module_ts_idx` ON `ability_log` (`module`,`ts`);',
    ],
  },
  {
    tag: '0005_ability_log_append_only',
    statements: [
      "CREATE TRIGGER ability_log_no_update BEFORE UPDATE ON ability_log\nBEGIN\n  SELECT RAISE(ABORT, 'ability_log is append-only');\nEND;",
      "CREATE TRIGGER ability_log_no_delete BEFORE DELETE ON ability_log\nBEGIN\n  SELECT RAISE(ABORT, 'ability_log is append-only');\nEND;",
    ],
  },
  {
    tag: '0006_sync_columns',
    statements: [
      'CREATE TABLE `sync_meta` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL\n);',
      'CREATE TABLE `sync_outbox` (\n\t`table_name` text NOT NULL,\n\t`row_id` text NOT NULL,\n\t`queued_at` integer NOT NULL,\n\tPRIMARY KEY(`table_name`, `row_id`)\n);',
      'ALTER TABLE `cards` ADD `updated_at` integer DEFAULT 0 NOT NULL;',
      'CREATE INDEX `cards_is_synced_idx` ON `cards` (`is_synced`);',
      'ALTER TABLE `palaces` ADD `is_synced` integer DEFAULT false NOT NULL;',
      'ALTER TABLE `palaces` ADD `updated_at` integer DEFAULT 0 NOT NULL;',
      'ALTER TABLE `sessions` ADD `is_synced` integer DEFAULT false NOT NULL;',
      'ALTER TABLE `sessions` ADD `updated_at` integer DEFAULT 0 NOT NULL;',
    ],
  },
  {
    tag: '0007_sync_dirty_triggers',
    statements: [
      "-- Hand-authored (triggers aren't representable in drizzle-kit snapshots, same as\n-- 0001/0005). Registered by hand in meta/_journal.json with a chain-linked\n-- snapshot, or migrations-consistency.test.ts fails.\n--\n-- Sync dirty-marking, per docs/superpowers/specs/2026-07-31-supabase-sync-design.md §2.1.\n--\n-- Why triggers rather than marking rows dirty at each call site: paths that\n-- mutate synced tables already exist and know nothing about sync (upsertPaoEntry\n-- rewrites cards.back/payload directly; reorderLoci rewrites every locus\n-- position). Relying on every current and future query function to remember\n-- `is_synced = 0` is exactly the invariant this codebase already chose to put in\n-- the database instead — see the append-only triggers in 0001/0005.\n--\n-- The `WHEN NEW.is_synced = OLD.is_synced` guard is what lets the sync writer\n-- flip a row to is_synced = 1 without the trigger immediately dirtying it again.\n-- SQLite's recursive triggers are off by default, so the inner UPDATE does not\n-- re-fire regardless.\n\n-- Backfill: existing rows predate the column and default to 0, which would make\n-- every one of them look older than any incoming row. Seed from the row's own\n-- creation time so a first sync compares something meaningful.\nUPDATE cards SET updated_at = created_at WHERE updated_at = 0;",
      'UPDATE palaces SET updated_at = created_at WHERE updated_at = 0;',
      'UPDATE sessions SET updated_at = started WHERE updated_at = 0;',
      "-- ---------------------------------------------------------------------------\n-- Class C mutable rows: any update marks the row dirty and stamps updated_at.\n-- Millisecond precision (strftime('%s') would only give whole seconds, too\n-- coarse for the updated_at tie-break in resolveRow).\n-- ---------------------------------------------------------------------------\nCREATE TRIGGER cards_mark_dirty AFTER UPDATE ON cards\nWHEN NEW.is_synced = OLD.is_synced\nBEGIN\n  UPDATE cards\n  SET is_synced = 0,\n      updated_at = CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)\n  WHERE id = NEW.id;\nEND;",
      "CREATE TRIGGER palaces_mark_dirty AFTER UPDATE ON palaces\nWHEN NEW.is_synced = OLD.is_synced\nBEGIN\n  UPDATE palaces\n  SET is_synced = 0,\n      updated_at = CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)\n  WHERE id = NEW.id;\nEND;",
      "CREATE TRIGGER sessions_mark_dirty AFTER UPDATE ON sessions\nWHEN NEW.is_synced = OLD.is_synced\nBEGIN\n  UPDATE sessions\n  SET is_synced = 0,\n      updated_at = CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)\n  WHERE id = NEW.id;\nEND;",
      "-- ---------------------------------------------------------------------------\n-- Class D: a palace's loci list is ONE logical value versioned by the palace\n-- row (design doc §3.4). Any locus change dirties the parent palace, never the\n-- locus itself — which is what keeps the whole-list merge incapable of\n-- violating UNIQUE(palace_id, position).\n-- ---------------------------------------------------------------------------\nCREATE TRIGGER loci_bump_palace_insert AFTER INSERT ON loci\nBEGIN\n  UPDATE palaces\n  SET is_synced = 0,\n      updated_at = CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)\n  WHERE id = NEW.palace_id;\nEND;",
      "CREATE TRIGGER loci_bump_palace_update AFTER UPDATE ON loci\nBEGIN\n  UPDATE palaces\n  SET is_synced = 0,\n      updated_at = CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)\n  WHERE id = NEW.palace_id;\nEND;",
      "CREATE TRIGGER loci_bump_palace_delete AFTER DELETE ON loci\nBEGIN\n  UPDATE palaces\n  SET is_synced = 0,\n      updated_at = CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)\n  WHERE id = OLD.palace_id;\nEND;",
      "-- ---------------------------------------------------------------------------\n-- Class A append-only tables: queue inserts in sync_outbox.\n--\n-- These tables CANNOT use is_synced — their append-only triggers abort any\n-- UPDATE, including one that only flips a sync flag, so a row could never be\n-- marked clean again. Queuing the id in a separate table is the only mechanism\n-- compatible with the append-only guarantee.\n-- ---------------------------------------------------------------------------\nCREATE TRIGGER review_log_queue_push AFTER INSERT ON review_log\nBEGIN\n  INSERT OR IGNORE INTO sync_outbox (table_name, row_id, queued_at)\n  VALUES ('review_log', NEW.id, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER));\nEND;",
      "CREATE TRIGGER ability_log_queue_push AFTER INSERT ON ability_log\nBEGIN\n  INSERT OR IGNORE INTO sync_outbox (table_name, row_id, queued_at)\n  VALUES ('ability_log', NEW.id, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER));\nEND;",
      "CREATE TRIGGER assessments_queue_push AFTER INSERT ON assessments\nBEGIN\n  INSERT OR IGNORE INTO sync_outbox (table_name, row_id, queued_at)\n  VALUES ('assessments', NEW.id, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER));\nEND;",
    ],
  },
];
