// AUTO-GENERATED by scripts/bundle-migrations.mjs — do not edit.
export interface Migration {
  tag: string;
  statements: string[];
}

export const MIGRATIONS: Migration[] = [
  {
    tag: '0000_known_mephisto',
    statements: [
      'CREATE TABLE `ability_ratings` (\n\t`module` text PRIMARY KEY NOT NULL,\n\t`elo` real NOT NULL,\n\t`updated_at` integer NOT NULL\n);',
      'CREATE TABLE `assessments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`instrument` text NOT NULL,\n\t`raw_score` real NOT NULL,\n\t`normalized` real,\n\t`ts` integer NOT NULL\n);',
      'CREATE TABLE `cards` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`module` text NOT NULL,\n\t`front` text NOT NULL,\n\t`back` text NOT NULL,\n\t`payload` text,\n\t`created_at` integer NOT NULL,\n\t`is_synced` integer DEFAULT false NOT NULL,\n\t`is_deleted` integer DEFAULT false NOT NULL\n);',
      'CREATE INDEX `cards_module_is_deleted_idx` ON `cards` (`module`,`is_deleted`);',
      'CREATE TABLE `fsrs_state` (\n\t`card_id` text PRIMARY KEY NOT NULL,\n\t`due` integer NOT NULL,\n\t`stability` real NOT NULL,\n\t`difficulty` real NOT NULL,\n\t`reps` integer NOT NULL,\n\t`lapses` integer NOT NULL,\n\t`phase` text NOT NULL,\n\t`scheduled_days` integer NOT NULL,\n\t`learning_steps` integer NOT NULL,\n\t`last_review` integer,\n\tFOREIGN KEY (`card_id`) REFERENCES `cards`(`id`) ON UPDATE no action ON DELETE no action\n);',
      'CREATE INDEX `fsrs_state_due_idx` ON `fsrs_state` (`due`);',
      'CREATE TABLE `review_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`card_id` text NOT NULL,\n\t`ts` integer NOT NULL,\n\t`rating` text NOT NULL,\n\t`elapsed_ms` integer NOT NULL,\n\t`difficulty` real NOT NULL,\n\t`stability` real NOT NULL,\n\t`retrievability` real NOT NULL,\n\tFOREIGN KEY (`card_id`) REFERENCES `cards`(`id`) ON UPDATE no action ON DELETE no action\n);',
      'CREATE INDEX `review_log_card_id_idx` ON `review_log` (`card_id`);',
      'CREATE INDEX `review_log_ts_idx` ON `review_log` (`ts`);',
      'CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`started` integer NOT NULL,\n\t`ended` integer,\n\t`module` text NOT NULL,\n\t`items` integer DEFAULT 0 NOT NULL,\n\t`accuracy` real DEFAULT 0 NOT NULL\n);',
    ],
  },
  {
    tag: '0001_review_log_append_only',
    statements: [
      "CREATE TRIGGER review_log_no_update BEFORE UPDATE ON review_log\nBEGIN\n  SELECT RAISE(ABORT, 'review_log is append-only');\nEND;",
      "CREATE TRIGGER review_log_no_delete BEFORE DELETE ON review_log\nBEGIN\n  SELECT RAISE(ABORT, 'review_log is append-only');\nEND;",
    ],
  },
  {
    tag: '0002_robust_arclight',
    statements: ['ALTER TABLE `assessments` ADD `payload` text;'],
  },
  {
    tag: '0003_tranquil_guardsmen',
    statements: [
      'CREATE TABLE `loci` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`palace_id` text NOT NULL,\n\t`position` integer NOT NULL,\n\t`label` text NOT NULL,\n\t`cue` text,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`palace_id`) REFERENCES `palaces`(`id`) ON UPDATE no action ON DELETE no action\n);',
      'CREATE INDEX `loci_palace_id_idx` ON `loci` (`palace_id`);',
      'CREATE UNIQUE INDEX `loci_palace_position_unq` ON `loci` (`palace_id`,`position`);',
      'CREATE TABLE `palaces` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`is_deleted` integer DEFAULT false NOT NULL\n);',
    ],
  },
];
